<a href="https://colab.research.google.com/github/AymenBbkr/dbcapibackend/blob/main/45.%20Day45%20KNN%20Classification(IRIS)/Day45_KNN_Classification(Iris).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                      Day45: KNN Classification (Iris)  By: Loga Aswin

In [12]:
#importing libraries
import numpy as np
import pandas as pd

**Data Pre-processing :**

In [13]:
# Importing the dataset
df = pd.read_csv('/content/Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [14]:
df.shape

(150, 6)

In [15]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [17]:
df.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [18]:
df.Species.value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [19]:
df['Species'] = df['Species'].replace({'Iris-setosa':1, 'Iris-versicolor':2, 'Iris-virginica':3})

<ipython-input-19-7b8ea1d69a47>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Species'] = df['Species'].replace({'Iris-setosa':1, 'Iris-versicolor':2, 'Iris-virginica':3})


In [20]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        1
1   2            4.9           3.0            1.4           0.2        1
2   3            4.7           3.2            1.3           0.2        1
3   4            4.6           3.1            1.5           0.2        1
4   5            5.0           3.6            1.4           0.2        1

In [21]:
df.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
145  146            6.7           3.0            5.2           2.3        3
146  147            6.3           2.5            5.0           1.9        3
147  148            6.5           3.0            5.2           2.0        3
148  149            6.2           3.4            5.4           2.3        3
149  150            5.9           3.0            5.1           1.8        3

In [24]:
X = df.drop('Species', axis=1)
Y = df['Species']

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0)

In [41]:
from sklearn.neighbors import KNeighborsClassifier

**Creating and Training KNN Model:**

In [42]:
knn_clf = KNeighborsClassifier(n_neighbors=5, metric='euclidean', p=2)
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean')

**Predict Test Results:**

In [43]:
y_pred = knn_clf.predict(X_test)

In [44]:
pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})

Actual  Predicted
114       3          3
62        2          2
33        1          1
107       3          3
7         1          1
100       3          3
40        1          1
86        2          2
76        2          2
71        2          2
134       3          3
51        2          2
73        2          2
54        2          2
63        2          2
37        1          1
78        2          2
90        2          2
45        1          1
16        1          1
121       3          3
66        2          2
24        1          1
8         1          1
126       3          3
22        1          1
44        1          1
97        2          2
93        2          2
26        1          1
137       3          3
84        2          2
27        1          1
127       3          3
132       3          3
59        2          2
18        1          1
83        2          2
61        2          2
92        2          2
112       3          3
2         1          1
141       3          3
43        1          1
10        1          1

**Model Evaluation Metrics**

In [45]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

score = accuracy_score(y_test, y_pred)
print(score)

1.0


In [46]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [48]:
m1 = confusion_matrix(y_test, y_pred)
print(m1)

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]


In [50]:
from sklearn.metrics import log_loss

# Get predicted probabilities for train and test sets
y_train_prob = knn_clf.predict_proba(X_train)
y_test_prob = knn_clf.predict_proba(X_test)

# Get predicted class labels for train and test sets using argmax
y_train_pred = np.argmax(y_train_prob, axis=1) +1 #add 1 to align with your class encoding
y_test_pred = np.argmax(y_test_prob, axis=1) +1 #add 1 to align with your class encoding


train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

train_loss = log_loss(y_train, y_train_prob)
test_loss = log_loss(y_test, y_test_prob)

print("Train Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)
print("Train Loss:", train_loss)
print("Test Loss:", test_loss)

Train Accuracy: 1.0
Test Accuracy: 1.0
Train Loss: 0.018230718597988974
Test Loss: 0.009917491169520645
